# Generated by Django 3.2 on 2023-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=150, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
