version: "3.3"
services:
    db:
      container_name: zebrand_db
      image: "postgres:13"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data/
      ports:
        - "5435:5432"
      restart: unless-stopped
      env_file: ../.env
    webapp:
      container_name: zebrand_webapp
      build:
        context: ../
        dockerfile: ./compose/Dockerfile
      volumes:
        - ../../source:/www/source
      ports:
        - "8000:8000"
      restart: unless-stopped
      depends_on:
        - db
      env_file: ../.env
