version: "3.3"
services:
    db:
      container_name: zebrand_db
      image: "postgres:13"
      volumes:
        - ../../volumes/db:/var/lib/postgresql/data
      ports:
        - "5435:5432"
      restart: unless-stopped
      env_file: ../.env
    webapp:
      container_name: zebrand_webapp
      build:
        context: ../
        dockerfile: ./compose/Dockerfile
      restart: unless-stopped
      env_file: ../.env
      entrypoint: ./entrypoint.sh
      volumes:
        - ../source:/www/source
      depends_on:
        - db
      ports:
        - "8000:8000"
    smtp-server:
      container_name: zebrand-back-smtp
      image: mailhog/mailhog:v1.0.1
      ports:
        - "8025:8025"
        - '1025:1025'
      restart: unless-stopped
    redis:
      image: redis:alpine
      container_name: zebrand-broker
      ports:
        - "6379:6379"
      volumes:
        - ../../volumes/zebrand-redis:/data